# Site settings
title: Shona Reed , User Experience Research and Service Design
email: ux@shonareed.com
url: https://shonareed.com
description: UX Research & Service Design, ten years experience, startups to Fortune 500, qualitative and quantitative research, genuine passion, Barcelona, London, San Francisco"
skills: "User Experience Research and Design"
meta_author: Reed Shona

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname


#  primary: 58A6A2 #80B3FF
#  primary-rgb: "24,288,156" #"128,179,255"
#  secondary: 000 #FD6E8A
#  secondary-dark: 233140 #A2122F

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 58A6A2 #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 000000 #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F


# Footer settings
footer:
  copyright: Shona Reed
  location: San Francisco
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/uxisready
  - title: github
    url: http://github.com/4point7

# Postal address (add as many lines as necessary)
address:
  - line:


# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
